repos:
  # https://github.com/pre-commit/pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  # gitup action
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint
  # https://pyproject-fmt.readthedocs.io/en/latest/
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "1.5.3"
    hooks:
      - id: pyproject-fmt
