name: "Pull request checklist"
on:
  pull_request_target:
    types:
      - ready_for_review
jobs:
  pull_request_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checklist
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: show_checklist
          message: |
            Checklist for pull request review.

            - [ ] Review METADATA:PRODUCT:DESCRIPTION field in parameter files (this should be equivalent to a commit message)
