---
name: Schema file validation
# Validate schema files against their metaschema.
# This workflow is to support developers.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  schema-validation:
    runs-on: ubuntu-latest
    container: ghcr.io/gammasim/simtools-prod:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install findutils
        run: |
          microdnf install -y findutils

      - name: Linter
        run: |
          pip install yamllint
          yamllint -d "{rules: {line-length: {max: 150}}}" schema/*.yml

      - name: Validate schema files.
        run: |
          for file in schema/*.yml; do
            echo "Testing schema $file"
            simtools-validate-file-using-schema \
              --file_name "$file" \
              --log_level DEBUG
          done
