---
name: Parameter file validation
# Validate parameter files against their schema.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  schema-validation:
    runs-on: ubuntu-latest
    container: ghcr.io/gammasim/simtools-prod:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install findutils
        run: |
          microdnf install -y findutils

      - name: Validate parameter files.
        run: |
          for file in $(find verified_model -name "*.json"); do
            PARAM=$(basename $file .json)
            echo "TESTING $file on $PARAM"
            simtools-validate-file-using-schema \
            --file_name $file \
            --schema schema/$PARAM.schema.yml
          done

      - name: Validate metadata.
        run: |
          echo "Validating metadata files."
